import json
import logging
import os
from typing import Dict, List, Optional, Tuple

from google import genai
from pydantic import BaseModel

from ..core.config import settings
from ..models import CaptionData
from ..utils.text_utils import format_multiline_caption as _format_multiline_caption

logger = logging.getLogger(__name__)

# Constants for translation settings
GEMINI_MODEL_TRANSLATE_CAPTION = "gemini-2.5-flash"
GEMINI_MODEL_TRANSLATE_TRANSCRIPTION = "gemini-2.5-pro"
GEMINI_MODEL_NATURAL_CAPTIONS = "gemini-2.5-flash"
DEFAULT_MAX_CHARS_PER_LINE = 40

# Subtitle best practices
MAX_CHARS_PER_LINE = 42  # Netflix standard
MAX_LINES_PER_CAPTION = 2
MAX_CAPTION_DURATION = 7.0  # seconds
MIN_CAPTION_DURATION = 0.7  # seconds
MAX_CPS = 21  # Characters per second


class NaturalCaption(BaseModel):
    """Schema for a natural caption generated by the LLM"""
    start_word_index: int
    end_word_index: int
    source_text: str  # Original language text
    translated_text: str  # Translated text
    speaker: Optional[str] = None


class TranslationGenerator:
    def __init__(self):
        # Get API key from environment variable or user config
        api_key = self._get_api_key()
        if not api_key:
            raise ValueError("Gemini API key not found. Please set it in environment variable GEMINI_API_KEY or configure it in the UI.")
        
        # The client gets the API key from environment or config
        self.client = genai.Client(api_key=api_key)

        # Maximum characters per line for captions
        self.max_chars_per_line = DEFAULT_MAX_CHARS_PER_LINE
    
    def _get_api_key(self) -> str:
        """Get API key from environment variable or user config file"""
        # First try environment variable
        env_key = os.getenv("GEMINI_API_KEY")
        if env_key:
            return env_key
        
        # Then try user config file
        config_dir = settings.data_dir / "config"
        api_key_config_path = config_dir / "api-key.json"
        
        if api_key_config_path.exists():
            with open(api_key_config_path, 'r', encoding='utf-8') as f:
                config_data = json.load(f)
                user_key = config_data.get("gemini_api_key")
                if user_key:
                    return user_key
    
        return None

    def format_multiline_caption(self, text: str) -> List[str]:
        """
        Formats text into one or two lines, prioritizing an inverted pyramid shape.
        Delegates to shared utility function.
        """
        return _format_multiline_caption(text, self.max_chars_per_line)
    
    def translate_caption(self, caption: str, source_language: str = "en", target_language: str = "ar") -> str:
        """Translate a single caption using Google Gemini (synchronous)."""
        logger.info(f"Translating caption ({source_language}->{target_language}): {caption}")
        prompt = f"Translate this {source_language} caption to {target_language} (Write nothing except the translation): {caption}"
        response = self.client.models.generate_content(
            model=GEMINI_MODEL_TRANSLATE_CAPTION, contents=prompt,
        )
        translated_text = response.text.replace("\n", " ").strip()
        translated_text = "\n".join(self.format_multiline_caption(translated_text))
        logger.info(f"Translated caption: {translated_text}")
        return translated_text
    
    def translate_transcription(self, transcription: List[CaptionData], source_language: str = "en", target_language: str = "ar") -> List[CaptionData]:
        """Translate the entire transcription in one shot (legacy 1:1 mapping)."""
        logger.info(f"Translating transcription {source_language}->{target_language} (segments={len(transcription)})")
        class TranslatedCaption(BaseModel):
            translation: str

        transcription_str = json.dumps([{"start_time": caption.start_time, "end_time": caption.end_time, "text": caption.text} for caption in transcription])
        prompt = (
            f"This is the transcription of a {source_language} video. "
            f"Please translate it into {target_language}. Return ONLY a JSON array matching the schema with the same number of list elements in the input transcription (One to One translation mapping).\n\n" + transcription_str
        )
        response = self.client.models.generate_content(
            model=GEMINI_MODEL_TRANSLATE_TRANSCRIPTION,
            contents=prompt,
            config={
                "response_mime_type": "application/json",
                "response_schema": list[TranslatedCaption],
            },
        )
        translations: List[TranslatedCaption] = response.parsed
        for idx in range(len(transcription)):
            translation_text = translations[idx].translation.replace("\n", " ").strip()
            transcription[idx].translation = "\n".join(self.format_multiline_caption(translation_text))
            logger.info(f"Translation for segment {idx}: {transcription[idx].translation}")

        return transcription

    def generate_natural_bilingual_captions(
        self, 
        words: List[Dict], 
        source_language: str = "en", 
        target_language: str = "ar"
    ) -> Tuple[List[Dict], List[Dict]]:
        """
        Generate natural captions in both source and target languages from word-level data.
        
        Unlike 1:1 translation, this method generates independently-segmented captions
        for each language, optimized for natural reading in that language.
        
        Args:
            words: List of word dicts with keys: word, start, end, probability, speaker (optional)
            source_language: Source language code (e.g., 'en')
            target_language: Target language code (e.g., 'ar')
            
        Returns:
            Tuple of (source_captions, translated_captions) where each caption has:
            start_time, end_time, text, speaker, confidence
        """
        if not words:
            return [], []
        
        logger.info(f"Generating natural bilingual captions: {source_language} -> {target_language} from {len(words)} words")
        
        # Prepare word data for LLM
        words_data = self._prepare_words_for_llm(words)
        
        # Build the prompt for bilingual natural caption generation
        prompt = self._build_natural_caption_prompt(words_data, source_language, target_language, len(words))
        
        # Call LLM
        response = self.client.models.generate_content(
            model=GEMINI_MODEL_NATURAL_CAPTIONS,
            contents=prompt,
            config={
                "response_mime_type": "application/json",
                "response_schema": list[NaturalCaption],
            },
        )
        
        generated_captions: List[NaturalCaption] = response.parsed
        
        # Convert to source and translated caption lists
        source_captions = []
        translated_captions = []
        
        for gen_cap in generated_captions:
            start_idx = max(0, min(gen_cap.start_word_index, len(words) - 1))
            end_idx = max(0, min(gen_cap.end_word_index, len(words) - 1))
            
            if start_idx > end_idx:
                start_idx, end_idx = end_idx, start_idx
            
            # Get timestamps from words
            start_time = words[start_idx].get("start", 0)
            end_time = words[end_idx].get("end", start_time)
            
            # Calculate confidence as average of word probabilities
            caption_words = words[start_idx:end_idx + 1]
            avg_confidence = sum(w.get("probability", 1.0) for w in caption_words) / max(1, len(caption_words))
            
            # Source caption
            source_captions.append({
                "start_time": start_time,
                "end_time": end_time,
                "text": gen_cap.source_text,
                "speaker": gen_cap.speaker,
                "confidence": avg_confidence
            })
            
            # Translated caption (same timing but different text)
            translated_captions.append({
                "start_time": start_time,
                "end_time": end_time,
                "text": gen_cap.translated_text,
                "speaker": gen_cap.speaker,
                "confidence": avg_confidence
            })
        
        logger.info(f"Generated {len(source_captions)} source and {len(translated_captions)} translated captions")
        return source_captions, translated_captions
    
    def _prepare_words_for_llm(self, words: List[Dict]) -> str:
        """Prepare word data for LLM prompt. Format: index|word|start|end|speaker"""
        lines = []
        for i, word in enumerate(words):
            speaker = word.get("speaker", "SPEAKER_00")
            text = word.get("word", "").strip()
            start = word.get("start", 0)
            end = word.get("end", start)
            lines.append(f"{i}|{text}|{start:.2f}|{end:.2f}|{speaker}")
        return "\n".join(lines)
    
    def _build_natural_caption_prompt(
        self, 
        words_data: str, 
        source_language: str, 
        target_language: str,
        word_count: int
    ) -> str:
        """Build prompt for natural bilingual caption generation"""
        
        # Language-specific guidance
        target_guidance = ""
        if target_language == "ar":
            target_guidance = """
ARABIC TRANSLATION RULES:
- Arabic reads right-to-left
- Arabic text is often more compact than English
- Use Arabic punctuation: ، (comma), ؛ (semicolon), ؟ (question mark)
- Translate naturally, not literally - capture the meaning and tone
- Keep formal/informal register consistent with the source
- For idioms, use equivalent Arabic expressions when possible"""
        
        return f"""You are an expert subtitle editor and translator. Given word-level transcription data, create natural, readable captions in BOTH languages simultaneously.

TASK: Create caption segments that work naturally in both {source_language} and {target_language}.

CAPTION RULES:
1. Group words into natural, complete thoughts
2. Each caption: max {MAX_CHARS_PER_LINE} chars/line, max {MAX_LINES_PER_CAPTION} lines
3. Duration: {MIN_CAPTION_DURATION}-{MAX_CAPTION_DURATION} seconds per caption
4. Reading speed: max {MAX_CPS} characters per second
5. ALWAYS start a new caption when speaker changes
6. Use \\n for line breaks (prefer inverted pyramid: longer line on top)
7. Keep related phrases together (don't split noun phrases, verb phrases)
8. End captions at natural pause points
{target_guidance}

INPUT FORMAT: index|word|start_time|end_time|speaker
Source Language: {source_language}
Target Language: {target_language}

WORD DATA:
{words_data}

OUTPUT: JSON array where each object has:
- start_word_index: first word index (0-based)
- end_word_index: last word index (inclusive)
- source_text: natural caption in {source_language} with line breaks
- translated_text: natural caption in {target_language} with line breaks
- speaker: primary speaker for this segment

CRITICAL:
- Cover ALL word indices from 0 to {word_count - 1} exactly once
- Both source_text and translated_text should be natural for their language
- Translated text should convey the same meaning but may use different sentence structure"""

    def _save_subtitles(self, project_dir, subtitles):
        """Save subtitles to a JSON file in the project directory"""
        subtitles_path = project_dir / "subtitles.json"
        with open(subtitles_path, 'w', encoding='utf-8') as f:
            # Convert CaptionData objects to dictionaries for JSON serialization
            subtitles_dict = [subtitle.dict() for subtitle in subtitles]
            json.dump(subtitles_dict, f, indent=2, ensure_ascii=False)
        logger.info(f"Subtitles saved successfully: {subtitles_path}")
